### ISSUE TITLE
Not Python 2.7 compatible. 

### ISSUE THREAD

**Issue by Crowlord** [gmccauley/OctoPrint-CooldownNotification#1]
This is a plugin I have been wanting forever as my printbite self releases at a lower temp. 

Like most installs mine is still on python 2.7 though. Any chance of dual compatibility?

**Comment by gmccauley** [comment]
Sorry about that.  It is 2.7 compatible.  I mistakenly thought that all new plugins should be 3+.  I've adjusted the compatibility settings to be 2.7+
