### ISSUE TITLE
Dosnt seem to do anything on Octoprint 1.8.4

### ISSUE THREAD

**Issue by ppastur** [gmccauley/OctoPrint-CooldownNotification#12]
Hi Im not sure if im doing something wrong but I cant seem to get it to issue M101 once the threshold temp is reached /passed.
![cooldown-SS](https://user-images.githubusercontent.com/91765182/193175532-75850062-35ba-467e-9de7-88ed38dd89fd.png)

- I clicked the test button and that works fine.
- I'm Using Octoprint 1.8.4
- To test, I am manually heating the print bed to 50 deg and then turning it off to allow it to cool naturally.  When the temp reaches 39 deg I expect it to issue M101 command (initiates PSU switch off) but it does nothing.
- I have tried to set debug logging on but I cant seem to get it to produce a log file 
- I have restarted Octoprint and re-tried the above

Can you help?

**Comment by gmccauley** [comment]
The intent of the plugin was to execute some GCODE after the bed had cooled to a certain temperature after a print completed, therefore the plugin doesn't actually start watching the temperature until a PrintDone or PrintFailed event is generated by OctoPrint.

**Comment by ppastur** [comment]
Oh I see. That’s very helpful to know. So to test , I will need to initiate a print and either cancel or complete the print for the plug-in to start watching temp and execute the code once threshold has been surpassed?

**Comment by ppastur** [comment]
Adding follow-up - I ran a print tonight and after it completed and the bed surpassed the threshold of 40deg, the printer switched off.  Super happy, thank you again.
