### ISSUE TITLE
Not working... (but may be)

### ISSUE THREAD

**Issue by wlbillmartin** [gmccauley/OctoPrint-CooldownNotification#9]
Before I say it's not working and we go back and forth with logs, lemmie clarify that when I installed, set up (35c), rebooted and heated the bed to 75 and then turned the heaters off, nothing happened.
Is this triggered by ANY drop below the set temp or ONLY if a print was performed?

**Comment by gmccauley** [comment]
It's only triggered after a print is finished or cancelled.
